### ISSUE TITLE
data.js:23 Uncaught (in promise) TypeError: Cannot read property 'frontmatter' of null

### ISSUE THREAD

**Issue by pasBone** [zouhangwithsweet/vuecomponent-seed#1]
直接拉的代码，然后运行，没有修改任何代码。

点击组件下面的`Button`就会报错，无法加载出文档的信息。

![image](https://user-images.githubusercontent.com/18027183/126270535-f3fdaf1d-bcfd-49bf-a008-59e5d7835825.png)

再刷新就直接报错了。

data.js:23 Uncaught (in promise) TypeError: Cannot read property 'frontmatter' of null

**Comment by zouhangwithsweet** [comment]
看起来是个 Vue 本身的报错，请问什么系统、node 版本、vite 版本、Vue 版本？

**Comment by zouhangwithsweet** [comment]
readme 已更新，预览文档需要先执行build，你可以先 yarn build:lib 然后再预览文档，晚点我会把 Win 平台的兼容问题处理好，感谢反馈
