### ISSUE TITLE
docs中 .MD内部的demo无法正确展示

### ISSUE THREAD

**Issue by xanggang** [zouhangwithsweet/vuecomponent-seed#10]
项目启动 `docs:dev`之后， md中的组件demo无法展示
```html
<demo-wrapper
  src="src/packages/button/demo"
/>
```
我并未找到组件demo-wrapper的相关使用方法，例如demos props如何获取和传入。

**Comment by zouhangwithsweet** [comment]
先 yarn build 试试，再 yarn doc:dev

**Comment by xanggang** [comment]
依然无法正常展示。 
操作系统： win10
node版本： v16.13.1
npm版本：8.1.2
目前操作：
master分支，全局替换关键字my-lib， yarn， yarn run build , yarn run doc：dev
页面http://localhost:3000/vuecomponent-seed/zh-CN/components/button.html中`demo-wrapper`无内容，页面无脚本错误

**Comment by zouhangwithsweet** [comment]
手边暂时没有 win 电脑，晚点我试试

**Comment by byoungd** [comment]
> 手边暂时没有 win 电脑，晚点我试试

问个题外话，由于文档里没有提到，请问发布之后是否支持按需引入？

**Comment by zouhangwithsweet** [comment]
> > 手边暂时没有 win 电脑，晚点我试试
> 
> 
> 
> 问个题外话，由于文档里没有提到，请问发布之后是否支持按需引入？

组件需要自己实现。然后，打包产物支持按需引入。自己也做了一个 https://github.com/mand-mobile/mand-mobile-next

**Comment by CHANCCCZQ** [comment]
> 先 yarn build 试试，再 yarn doc:dev

我拉的最新代码，按照你说的处理了，依然无法显示。。。。

![image](https://user-images.githubusercontent.com/22274839/150901907-556e161c-eff6-416e-94b0-5611130dc9f3.png)

**Comment by zouhangwithsweet** [comment]
> > 先 yarn build 试试，再 yarn doc:dev
> 
> 我拉的最新代码，按照你说的处理了，依然无法显示。。。。
> 
> ![image](https://user-images.githubusercontent.com/22274839/150901907-556e161c-eff6-416e-94b0-5611130dc9f3.png)

windows ? 好家伙，我得找个网吧，或者买个电脑

**Comment by zouhangwithsweet** [comment]
搞到一个电脑，排查到问题了。我在处理demo路径的时候没有兼容 windows https://github.com/zouhangwithsweet/fisand-doc/blob/feat_fisand_doc/src/node/markdownToVue.ts#L111.
稍晚点，我会修复。。。

**Comment by zouhangwithsweet** [comment]
已修复 fisand-doc 升级至 0.0.19 即可
