### ISSUE TITLE
关于使用jsx执行build命令失败的情况

### ISSUE THREAD

**Issue by EG8A25** [zouhangwithsweet/vuecomponent-seed#15]
组件中使用到了jsx去写渲染函数，执行build命令会报the jsx syntax extension is not currently enable，请问这个问题有解决方案吗？或者解决思路，谢谢

**Comment by zouhangwithsweet** [comment]
- 使用 ebsuild，可参考 https://esbuild.github.io/content-types/#auto-import-for-jsx
- 使用 babel, 可参考 https://vitejs.dev/plugins/#vitejs-plugin-vue-jsx

**Comment by zouhangwithsweet** [comment]
需要修改对应 `rollup.config.js` & `scripts/esbuild.ts` & `tsconfig.json`
