### ISSUE TITLE
引入less变量，build报错

### ISSUE THREAD

**Issue by jinxinkai** [zouhangwithsweet/vuecomponent-seed#16]
![image](https://user-images.githubusercontent.com/21239915/155417232-04469b3a-6235-4eaa-a0e7-a706e54df97d.png)
![image](https://user-images.githubusercontent.com/21239915/155417311-fab98ca8-c459-4fa1-a905-387920ba54c1.png)

**Comment by zouhangwithsweet** [comment]
- 是否 install `less` 呢？
- `rollup.confog.ts` 和 `esbuild.ts` 都修改了吗？

**Comment by jinxinkai** [comment]
想问一下 怎么build时也把less文件打包出来

**Comment by zouhangwithsweet** [comment]
现在的构建产物是什么？

**Comment by jinxinkai** [comment]
> 现在的构建产物是什么？

现在是css

**Comment by zouhangwithsweet** [comment]
less 建议直接硬编码维护哈，可以参考 element plus 如何维护sass的

**Comment by jinxinkai** [comment]
> less 建议直接硬编码维护哈，可以参考 element plus 如何维护sass的

好的  我试一下  感谢！
