### ISSUE TITLE
Use less instead of css

### ISSUE THREAD

**Issue by sumitkolhe** [zouhangwithsweet/vuecomponent-seed#17]
First of all thanks for the amazing work! Currently all the styles are inside the vue SFC and in stylus format, is there a way to have them in "less" and maybe in a separate file for each component like-

-- button/
---- button.vue
---- style.less
---- index.ts

**Comment by zouhangwithsweet** [comment]
I will seriously consider this suggestion and implement it :)

**Comment by sumitkolhe** [comment]
@zouhangwithsweet thank you. Let me know if I can help in any way.

**Comment by zouhangwithsweet** [comment]
> @zouhangwithsweet thank you. Let me know if I can help in any way.

First,
You can set the `preprocessLang` to `less`.
https://github.com/zouhangwithsweet/vue-components-lib-seed/blob/master/scripts/esbuild.ts#L29
https://github.com/zouhangwithsweet/vue-components-lib-seed/blob/master/scripts/rollup.config.ts#L27

Then, for splitting
set
```
<style src="./style.less" lang="less"></style>
```

At last,
change the template for generating `component`

https://github.com/zouhangwithsweet/vue-components-lib-seed/blob/master/scripts/_template/index.vue.hbs

**In fact, I expect the developer to be able to customize everything he wants, so I just provide the template code.** 
Hope to answer your suggestions :)

**Comment by sumitkolhe** [comment]
@zouhangwithsweet i already implemented this, seems to be working fine. Thanks! Can close this issue now :)
