### ISSUE TITLE
no loader is configured for ".ttf"

### ISSUE THREAD

**Issue by Linjx520074913** [zouhangwithsweet/vuecomponent-seed#20]
你好，我想加载 iconfont，npm run dev 的时候可以正常加载出图标，但是在 npm run build 的时候，却出现了 `src/assets/font/iconfont.css:5:11: error: No loader is configured for ".ttf" files: src/assets/font/iconfont.ttf?t=1641284086982
 > src/assets/font/iconfont.css:3:11:     5 │        url(error: 'iconfont.ttf?t=1641284086982') format('truetype');
      ╵            No loader is configured for ".woff2" files: src/assets/font/iconfont.woff2?t=1641284086982
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 │   src: url(
'iconfont.woff2?t=1641284086982') format('woff2'),
      ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ > src/assets/font/iconfont.css:4:11:
error:
No loader is configured for ".woff" files: src/assets/font/iconfont.woff?t=1641284086982
    4 │        url( > src/assets/font/iconfont.css:4:11: 'iconfont.woff?t=1641284086982'error: ) format('woff'),
      ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~No loader is configured for ".woff" files: src/assets/font/iconfont.woff?t=1641284086982


      ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
请问这得如何解决呢？

**Comment by zouhangwithsweet** [comment]
单独运行 `yarn build:bundle` `yarn build:lib`  看看是否正常，然后排查对应的 构建错误
