### ISSUE TITLE
写多个实例demo0,demo1,demo2,只有第一个才能展开代码

### ISSUE THREAD

**Issue by qc-z** [zouhangwithsweet/vuecomponent-seed#22]

**Comment by qc-z** [comment]
![image](https://user-images.githubusercontent.com/22362903/171418558-36f06a5f-6eb3-4195-a9a7-bb263b00e33f.png)

![image](https://user-images.githubusercontent.com/22362903/171418476-365e5fb3-7c04-4658-9793-84eb6d424957.png)

**Comment by zouhangwithsweet** [comment]
[WIP]: 这里我还没写完呢 :)
但是思路就是判断有没有后缀名，如果没有，就去 fs.read 路径下所有的 .vue 即可, 拼接成 source 即可；
https://github.com/zouhangwithsweet/vue-components-lib-seed/blob/master/docs/.vitepress/plugins/demo.ts#L46
很简单，但是我最近没啥空，感兴趣的哈，可以帮忙提个 PR

**Comment by qc-z** [comment]
@zouhangwithsweet 大佬赶紧写出来~

**Comment by zouhangwithsweet** [comment]
https://github.com/zouhangwithsweet/vue-components-lib-seed#use-demo-code-in-doc
