### ISSUE TITLE
请问下是否支持 单组件版本控制，单组件changelog

### ISSUE THREAD

**Issue by ziyingjie** [zouhangwithsweet/vuecomponent-seed#23]
Thanks

**Comment by zouhangwithsweet** [comment]
现在不支持

**Comment by ziyingjie** [comment]
> 现在不支持

大佬能给个思路吗，还望不吝赐教，多谢多谢

**Comment by zouhangwithsweet** [comment]
我的感觉是，可以但没必要

**Comment by ziyingjie** [comment]
哈哈 受教啦，by the way [vue-components-lib-seed](https://github.com/zouhangwithsweet/vue-components-lib-seed)这个应该也支持基于vant等移动端组件库二次封装吧

**Comment by zouhangwithsweet** [comment]
支持:)
