### ISSUE TITLE
构建后内联vue导致和业务项目依赖的vue不是同一个，inject provide 共享出错

### ISSUE THREAD

**Issue by nelk98** [zouhangwithsweet/vuecomponent-seed#24]
我尝试在 rollup.config.js 添加配置 external: ['vue'] 解决了这个问题，请大佬指教。

**Comment by zouhangwithsweet** [comment]
看起来 是有的 晚点我看下
https://github.com/zouhangwithsweet/vue-components-lib-seed/blob/master/scripts/rollup.config.ts#L65

**Comment by nelk98** [comment]
多谢，我发现本地代码和您仓库的不一致，修改后已解决。
