### ISSUE TITLE
在组件中使用jsx

### ISSUE THREAD

**Issue by xanggang** [zouhangwithsweet/vuecomponent-seed#25]
当我在组件中使用jsx， 然后在doc中使用这个组件的时候，提示`React is not defined`

```
:::demo  
src/packages/base/demo/demo2.vue
:::
```
```
<template>
  <BasicHelp text='this help text'></BasicHelp> // 这个组件中包含jsx代码
</template>

<script setup lang="ts">
import { BasicHelp } from 'dc-quick-ui/base'
</script>

<script lang="ts">
export default {
  name: 'Demo2',
  title: '基本',
}
</script>

```

似乎esbuild的时候没有对jsx的支持

**Comment by zouhangwithsweet** [comment]
dc-quick-ui/base 是 react 的组件吗？
这个模版现在是不支持 jsx 的，未来大概率也不会支持；你可以自己在本地改造即可

**Comment by xanggang** [comment]
目前通过在`esbuild`中添加`unplugin-vue-jsx/esbuild`添加了对jsx的支持， 但是奇怪的是这个jsx插件只能编译`.jsx`拓展名的文件， 对于`.vue`文件中的`render`函数和`tsx`代码都不识别。
考虑到在编写组件的时候 jsx还是挺用的， 希望后续能添加对jsx的支持。
