### ISSUE TITLE
我是中国人，发中文没问题吧？

### ISSUE THREAD

**Issue by Luxii44** [zouhangwithsweet/vuecomponent-seed#29]
我是用ts-morph生成vue文件和ts文件的声明文件d.ts，但是在getPreEmitDiagnostics的时候，我packages中的我们wmcomponent文件夹中的component.ts中的’‘’import type { Plugin } from 'vue'‘’‘报了‘’‘Module '"vue"' has no exported member 'Plugin'’‘’的错误，而且在packages文件夹中凡是引用到了vue中的文件就会报类似的错误，不知道是什么原因
项目地址在：https://github.com/Luxii44/elementcpcomponent

**Comment by Luxii44** [comment]
希望您能看一下，给我点提示

**Comment by zouhangwithsweet** [comment]
看看是不是 vue 版本得问题呢

**Comment by zouhangwithsweet** [comment]
你这个仓库地址 404

**Comment by Luxii44** [comment]
> 你这个仓库地址 404

sorry，我忘记把库公开出来了，现在可以了

**Comment by Luxii44** [comment]
> 看看是不是 vue 版本得问题呢

我的vue版本是3.2.45，难道是太新了？

**Comment by zouhangwithsweet** [comment]
哈哈 看不出来，可以自己 debug 以下

**Comment by Luxii44** [comment]
> 哈哈 看不出来，可以自己 debug 以下

我是在getPreEmitDiagnostics中，也就是ts的类型校验中，编辑器报的这个错，这个错我找了几天都不知道问题出在哪里，您在使用ts-morph的时候是否有过类型校验不通过的情况呢？

**Comment by zouhangwithsweet** [comment]
> > 哈哈 看不出来，可以自己 debug 以下
> 
> 我是在getPreEmitDiagnostics中，也就是ts的类型校验中，编辑器报的这个错，这个错我找了几天都不知道问题出在哪里，您在使用ts-morph的时候是否有过类型校验不通过的情况呢？

没有哎

**Comment by Luxii44** [comment]
> > > 哈哈 看不出来，可以自己 debug 以下
> > 
> > 
> > 我是在getPreEmitDiagnostics中，也就是ts的类型校验中，编辑器报的这个错，这个错我找了几天都不知道问题出在哪里，您在使用ts-morph的时候是否有过类型校验不通过的情况呢？
> 
> 没有哎

我虽然暂时解决了问题，但是我还是存有疑惑，因为我把pnpm的hoist的值改为false后就没有那个错误了，但是hoist为true的时候才能实现pnpm的最外层依赖支持，我这么设只是权宜之策，并不是最好的方法
