### ISSUE TITLE
unused code 

### ISSUE THREAD

**Issue by NomadBin** [zouhangwithsweet/vuecomponent-seed#7]
I guess the code file is probaly unused:
https://github.com/zouhangwithsweet/vuecomponent-seed/blob/master/src/packages/button/demo/index.vue

**Comment by NomadBin** [comment]
If not in use. I think the code should be deleted, Because it would confuse the code.

**Comment by zouhangwithsweet** [comment]
这是为了开发时预览，配合 vite-plugin-pages；docs 使用的组件是打包后的，当然，看用户的选择。docs/vite.config.ts 可以自行处理 alias

**Comment by NomadBin** [comment]
好的，明白了！ 感谢你的回复
