### ISSUE TITLE
demo 也应该支持中英文切换

### ISSUE THREAD

**Issue by NomadBin** [zouhangwithsweet/vuecomponent-seed#8]
修改思路:
1. 将 `src/template/*/demo` 修改为  `src/template/*/demo/zhcn` 与  `src/template/*/demo/enus`
2. vitepress的demo plugin中的正则由 `/src=("|')src\/packages\/[A-z]+-?[A-z]+\/demo("|')/` 变为 `/src=("|')src\/packages\/[A-z]+-?[A-z]+\/demo(\/[\w]+)?("|')/`
3. 组件的readme.md中指定对应的语言demo `<demo-wrapper
  src="src/packages/button/demo/zhcn"
/>` 
4. 修改 script/_template

---
如果觉得ok的话，我可以提个pull request!

**Comment by zouhangwithsweet** [comment]
我已经采用 fisand-doc，这是一个对 vitepress 的非深度定制，你看看能不能实现你的需求。
ps: 个人觉得 demo 其实还好，对国际化的要求没有那么大；一般 demo 也只是跑 example，看一看用的；文档的本身才是核心；

**Comment by NomadBin** [comment]
好的。感谢！  我的需求场景可能要对vitepress的部分进行修改。
ps: 所以我会更倾向于以前的方式，将vitepress中的自定义部分之间放在docs中。 (你这种抽取成 fisand-doc的形式也不错! )

**Comment by zouhangwithsweet** [comment]
> 好的。感谢！ 我的需求场景可能要对vitepress的部分进行修改。
> ps: 所以我会更倾向于以前的方式，将vitepress中的自定义部分之间放在docs中。 (你这种抽取成 fisand-doc的形式也不错! )

fisand-doc 也支持所有的 vitepress 自定义；你可以试试；我只是加了几个feature
1. 内置 windincss
2. 支持暗黑模式，以及更符合组件库的首页
3. 支持单一demo，和批量 demo 引入
4. （一部分的 i18n 的能力

当然如果你有更复杂的场景需求，我的建议可以考虑也自定义一个··· :)
