### ISSUE TITLE
更新下来的代码不能在文档中展示组件示例

### ISSUE THREAD

**Issue by long-hai-yang** [zouhangwithsweet/vuecomponent-seed#9]
## 更新下来的代码不能在文档中展示组件示例
 文档中里面对`在文档中使用组件 demo`里面对`DemoWrapper`组件的说明的链接，在对应目录里面也没有看到对应的文件

**Comment by zouhangwithsweet** [comment]
目前的文档已经收归到 [fisandoc](https://zouhangwithsweet.github.io/fisand-doc/)，可以看下。晚点我更新下文档

**Comment by MaybeQHL** [comment]
我也遇到同样的问题
